// *****************************************************************************************
//
// File description:
//
// Author:	Joao Costa
// Purpose:	Provide enum to string mappings for CPU features
//
// *****************************************************************************************

osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_none,		= 0,	"",		"None"						)

// Intel Base features
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_fpu, 		,	"fpu", 		"Floating Point Unit"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_vme, 		,	"vme",		"Virtual 8086 mode enhancements"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_de, 		,	"de",		"Debugging Extensions"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_pse, 		,	"pse",		"Page Size Extensions"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_tsc, 		,	"tsc",		"Time Stamp Counter"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_msr, 		,	"msr",		"Model-Specific Registers"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_pae, 		,	"pae",		"Physical Address Extensions"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_mce, 		,	"mce",		"Machine Check Exception"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_cx8, 		,	"cx8",		"CMPXCHG8 instruction "				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_apic, 		,	"apic",		"Onboard APIC"					)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_sep, 		,	"sep",		"SYSENTER/SYSEXIT"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_mtrr, 		,	"mtrr",		"Memory Type Range Registers"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_pge, 		,	"pge",		"Page Global Enable"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_mca, 		,	"mca",		"Machine Check Architecture"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_cmov, 		,	"cmov",		"conditional move"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_pat, 		,	"pat",		"Page Attribute Table"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_pse36, 		,	"pse36",	"36-bit PSEs (huge pages)"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_psn, 		,	"psn",		"Processor serial number"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_clflush,		,	"clflush",	"Cache Line Flush instruction"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_dts, 		,	"dts",		"Debug Store"					)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_acpi, 		,	"acpi",		"ACPI via MSR"					)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_mmx, 		,	"mmx",		"Multimedia Extensions"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_fxsr, 		,	"fxsr",		"FXSAVE/FXRSTOR"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_ss, 		,	"ss",		"CPU self snoop"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_ht, 		,	"ht",		"Hyper-Threading and/or multi-core"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_tm, 		,	"tm",		"Automatic clock control (Thermal Monitor)"	)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_ia64, 		,	"ia64",		"Itanium Architecture 64-bit"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_pbe, 		,	"pbe",		"Pending Break Enable "				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_pclmulqdq,	,	"pclmulqdq",	"Carry-Less Multiplication of Quadword"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_dtes64, 		,	"dtes64",	" 64-bit Debug Store"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_monitor,		,	"monitor",	"Monitor/Mwait support"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_ds_cpl, 		,	"ds_cpl",	"CPL Qual. Debug Store"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_vmx, 		,	"vmx",		"Hardware virtualization"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_smx, 		,	"smx",		"Safer mode"					)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_est, 		,	"est",		"Enhanced SpeedStep"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_tm2, 		,	"tm2",		"Thermal Monitor 2"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_cid, 		,	"cid",		"Context ID"					)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_sdbg, 		,	"sdbg",		"Silicon debug"					)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_fma, 		,	"fma",		"Fused multiply-add"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_cx16, 		,	"cx16",		"CMPXCHG16B"					)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_xtpr, 		,	"xtpr",		"Send Task Priority Messages"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_pdcm, 		,	"pdcm",		"Performance Capabilities"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_pcid, 		,	"pcid",		"Process Context Identifiers"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_dca, 		,	"dca",		"Direct Cache Access"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_x2apic, 		,	"x2apic",	"Advanced Programmable Interrupt Controller"	)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_movbe, 		,	"movbe",	"Move Data After Swapping Bytes"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_popcnt, 		,	"popcnt",	"Bit count"					)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_tsc_dt, 		,"tsc_deadline_timer",	"Tsc deadline timer"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_xsave, 		,	"xsave",	"Save Processor Extended States"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_xsaveopt, 	,	"xsaveopt",	"Save Processor Extended States Optimized"	)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_f16c, 		,	"f16c",		"16-bit fp conversions"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_rdrand, 		,	"rdrand",	"Read Random Number"				)


// Leaf7:
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_fsgsbase, 	,	"fsgsbase",	"Access to base of %fs and %gs"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_sgx, 		,	"sgx",		"Software Guard Extensions"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_bmi1, 		,	"bmi1",		"Bit Manipulation Instruction Set 1"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_hle, 		,	"hle",		"Hardware Lock Elision"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_smep, 		,	"smep",		"Supervisor Mode Execution Prevention"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_bmi2, 		,	"bmi2",		"Bit Manipulation Instruction Set 2"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_erms, 		,	"erms",		"Enhanced REP MOVSB/STOSB"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_invpcid,		,	"invpcid",	"INVPCID instruction"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_rtm, 		,	"rtm",		"Restricted Transactional Memory"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_pqm, 		,	"pqm",		"Platform Quality of Service Monitoring"	)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_mpx, 		,	"mpx",		"Memory Protection Extensions"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_pqe, 		,	"pqe",		"Platform Quality of Service Enforcement"	)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_rdseed, 		,	"rdseed",	"RDSEED instruction"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_adx, 		,	"adx",		"Multi-Precision Add-Carry Extensions"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_smap, 		,	"smap",		"Supervisor Mode Access Prevention"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_pcommit,		,	"pcommit",	"PCOMMIT instruction"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_clflushopt,	,	"clflushopt",	"CLFLUSHOPT instruction"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_clwb, 		,	"clwb",		"CLWB instruction"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_intel_pt, 	,	"intel_pt",	"Intel Processor Trace"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_prefetchwt1,	,	"prefetchwt1",	"PREFETCHWT1 instruction"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_waitpkg,		,	"waitpkg",	"waitpkg"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_shstk, 		,	"shstk",	"shstk"						)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_cldemote,	,	"cldemote",	"Cache line demote"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_sgx_lc, 		,	"sgx_lc",	"SGX Launch Configuration"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_enqcmd, 		,	"enqcmd",	"Enqueue Stores"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_movdiri, 	,	"movdiri",	"MOVDIRI"					)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_movdir64b, 	,	"movdir64b",	"MOVDIR64B"					)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_fsrm, 		,	"fsrm",		"Fast Short REP MOVSB"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_md_clear,	,	"md_clear",	"VERW instruction clears CPU buffers"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_tsx_force_abort,	,	"tsx_force_abort","tsx_force_abort"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_serialize, 	,	"serialize",	"Serialize instruction execution"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_hybrid, 		,	"hybrid",	"Hybrid"					)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_tsxldtrk,	,	"tsxldtrk",	"TSX suspend load address tracking"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_pconfig,		,	"pconfig",	"Platform configuration"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_ibt, 		,	"ibt",		"ibt"						)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_spec_ctrl,	,	"spec_ctrl",	"Speculation Control"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_stibp, 		,	"stibp",	"Single Thread Indirect Branch Predictor"	)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_sscm1, 		,	"sscm1",	"Speculative Side Channel Mitigations 1"	)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_sscm2, 		,	"sscm2",	"Speculative Side Channel Mitigations 2"	)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_ssbd, 		,	"ssbd",		"Speculative Store Bypass Disable"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_umip, 		,	"umip",		"User Mode Instruction Protection"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_pku, 		,	"pku",		"Protection Keys for Userspace"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_ospke, 		,	"ospke",	"OS Protection Keys Enable"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_gfni, 		,	"gfni",		"Galois Field New Instructions"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_vaes, 		,	"vaes",		"Vector AES"					)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_vpclmulqdq,	,	"vpclmulqdq",	"Carry-Less Multiplication Double Quadword"	)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_la57, 		,	"la57",		"5-level page tables"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_rdpid, 		,	"rdpid",	"RDPID instruction"				)


/*
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_, 		,	"",		""			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_, 		,	"",		""			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_, 		,	"",		""			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_, 		,	"",		""			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_, 		,	"",		""			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_, 		,	"",		""			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_, 		,	"",		""			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_, 		,	"",		""			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_, 		,	"",		""			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_, 		,	"",		""			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_, 		,	"",		""			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_, 		,	"",		""			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_, 		,	"",		""			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_, 		,	"",		""			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_, 		,	"",		""			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_, 		,	"",		""			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_, 		,	"",		""			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_, 		,	"",		""			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_, 		,	"",		""			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_, 		,	"",		""			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_, 		,	"",		""			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_, 		,	"",		""			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_, 		,	"",		""			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_, 		,	"",		""			)


*/
//osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_, 		,	"",		""			)

// Thermal and Power Management
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_dtherm, 		,	"dtherm",	"Digital thermal sensor"			)
// IDA => Turbo Boost Technology
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_ida, 		,	"ida",		"Intel Dynamic Acceleration"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_arat, 		,	"arat",		"Always Running APIC Timer"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_pln, 		,	"pln",		"Intel Power Limit Notification"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_ecmd, 		,	"ecmd",		"Clock Modulation duty cycle extension"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_pts, 		,	"pts",		"Intel Package Thermal Status"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_hwp, 		,	"hwp",		"Intel Hardware P-states"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_hwp_notify,	,	"hwp_notify",	"HWP notification"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_hwp_act_win,	,	"hwp_act_window","HWP Activity Window"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_hwp_epp,		,	"epp",		"HWP Energy Performance Preference"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_hwp_pkg_req,	,	"hwp_pkg_req",	"HWP package-level request"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_hdc, 		,	"hdc",		"HDC base registers supported"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_tboost_max, 	,	"tbm",		"Turbo Boost Max 3.0"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_hwp_cap,		,	"hwp_cap",	"HWP Capacbilities"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_hwp_peci, 	,	"hwp_peci",	"HWP PECI override"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_hwp_flex,	,	"hwp_flex",	"Flexible HWP"					)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_fam,		,	"fam",		"Fast Access Mode"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_hw_feedback, 	,	"hw_feedback",	"HW Feedback"					)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_lp_ignore,	,	"lp_ignore",	"Ignore Iddle Logical Processor HWP request"	)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_hw_cfc, 		,	"hw_cfc",	"Hardware Coordination Feedback Capability"	)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_enegy_bias,	,	"enegy_bias",	"Performance-energy bias preference"		)


// Security features
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_sha, 		,	"sha",		"Intel SHA extensions"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_aes,		,	"aes",		"Advanced Encryption Standard"			)

// SSE features
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_sse, 		,	"sse",		"SSE vector instructions"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_sse2,		,	"sse2",		"SSE vector instructions 2"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_sse3, 		,	"sse3",		"SSE vector instructions 3"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_ssse3, 		,	"ssse3",	"Supplemental SSE3"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_sse4_1, 		,	"sse4_1",	"SSE vector instructions"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_sse4_2, 		,	"sse4_2",	"SSE vector instructions"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_sse4a, 		,	"sse4a",	"SSE vector instructions"			)

// AVX features
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_avx,		,	"avx",			"Advanced Vector Extensions"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_avx2, 		,	"avx2",			"AVX 2"					)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_avx512f, 	,	"avx512f",		"AVX 512 Foundation"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_avx512vl,	,	"avx512vl",		"AVX Vector Length Extensions "		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_avx512bw,	,	"avx512bw",		"AVX Byte and Word"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_avx512dq,	,	"avx512dq",		"AVX Double and Quadword"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_avx512cd,	,	"avx512cd",		"AVX Conflict Detection"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_avx512er,	,	"avx512er",		"AVX Exponential and Reciprocal"	)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_avx512pf,	,	"avx512pf",		"AVX Prefetch Instructions"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_avx512vbmi,	,	"avx512vbmi",		"AVX Vector Byte Manipulation"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_avx512ifma,	,	"avx512ifma",		"AVX Integer Fused Multiply Add"	)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_avx5124vnniw,	,	"avx5124vnniw",		"AVX Vector Neural Network (Word variable precision)"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_avx5124fmaps,	,	"avx5124fmaps",		"AVX Fused Multiply Accumulation Packed Single precision"	)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_avx512vpopcntdq,	,	"avx512vpopcntdq",	"AVX Vector population count"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_avx512vbmi2,	,	"avx512vbmi2",		"AVX Vector Byte Manipulation 2"	)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_avx512vnni,	,	"avx512vnni",		"AVX Vector Neural Network"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_avx512bf16,	,	"avx512bf16",		"AVX Vector Neural Network supporting BFLOAT16"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_avx512bitalg,	,	"avx512bitalg",		"AVX Bit Algorithms"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_avx512vp2i,	,	"avx512vp2i",		"AVX Vector Pair Intersection to a Pair of Mask Register"	)

// AMD specific
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_syscall, 	,	"syscall",		"SYSENTER/SYSEXIT"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_mp, 		,	"mp",			"Multiprocessor Capable"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_nx, 		,	"nx",			"Execute Disable"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_mmxext, 		,	"mmxext",		"AMD MMX extensions"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_fxsr_opt, 	,	"fxsr_opt",		"FXSAVE/FXRSTOR optimizations"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_pdpe1gb,		,	"pdpe1gb",		"One GB pages"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_rdtscp, 		,	"rdtscp",		"Read Time-Stamp Counter and Processor ID"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_lm, 		,	"lm",			"Long Mode (64 bits)"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_3dnowext,	,	"3DNow_ext",		"AMD 3DNow! extensions"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_3dnow, 		,	"3DNow",		"AMD vector instructions"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_hypervisor,	,	"hypervisor",		"Running on a hypervisor"		)

osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_lahf_lm, 	,	"lahf_lm",		"Load AH from Flags"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_cmp_legacy,	,	"cmp_legacy",		"HyperThreading valid?"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_svm, 		,	"svm",			"Secure virtual machine"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_extapic,		,	"extapic",		"Extended APIC space"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_cr8_legacy,	,	"cr8_legacy",		"CR8 in 32-bit mode"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_abm, 		,	"abm",			"Advanced Bit Manipulation"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_misalignsse,	,	"misalignsse",		"SSE instructions misaligned?"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_3dnowpref,	,	"3dnowprefetch",	"3DNow prefetch"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_osvw, 		,	"osvw",			"OS Visible Workaround"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_ibs, 		,	"ibs",			"Instruction Based Sampling"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_xop, 		,	"xop",			"XOP instruction set"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_skinit, 		,	"skinit",		"SKINIT/STGI"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_wdt, 		,	"wdt",			"Watchdog timer"			)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_lwp, 		,	"lwp",			"Light Weight Profiling"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_fma4, 		,	"fma4",			"4 operands MAC instructions"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_tce, 		,	"tce",			"Translation cache extension"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_nodeid_msr,	,	"nodeid_msr",		"NodeId MSR"				)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_tbm, 		,	"tbm",			"Trailing Bit Manipulation"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_topoext,		,	"topoext",		"Topology Extensions CPUID leafs"	)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_perfctr_core,	,	"perfctr_core",		"Core Performance Counter Extensions"	)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_perfctr_nb,	,	"perfctr_nb",		"NB Performance Counter Extensions"	)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_bpext, 		,	"bpext",		"Data breakpoint extension"		)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_ptsc, 		,	"ptsc",			"Performance time-stamp counter"	)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_perfctr_l2,	,	"perfctr_l2",		"L2 Performance Counter Extensions"	)
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_mwaitx, 		,	"mwaitx",		"MWAIT extension"			)
//osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_, 		,	"",		""			)

// Others
//osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_, 		,	"",		""			)


// MAX must be less than 256
osapi_machine_cpu_feature_X( osapi_machine_cpu_feature_max, ,			"",		"Max"			)
